### ISSUE TITLE
Notes on Celestron OAG Dimensions

### ISSUE THREAD

**Issue by Endymion42** [jlecomte/ascom-oag-focuser#10]
Attached are some notes on the critical dimensions of the Celestron OAG should you decide at some point to make a design for it.

[Notes on Celestron OAG Dimensions for ASCOM-OAG-FOCUSER Picture 1 .pdf](https://github.com/jlecomte/ascom-oag-focuser/files/14216520/Notes.on.Celestron.OAG.Dimensions.for.ASCOM-OAG-FOCUSER.Picture.1.pdf)
[Notes on Celestron OAG Dimensions for ASCOM-OAG-FOCUSER Picture 2 .pdf](https://github.com/jlecomte/ascom-oag-focuser/files/14216521/Notes.on.Celestron.OAG.Dimensions.for.ASCOM-OAG-FOCUSER.Picture.2.pdf)

**Comment by jlecomte** [comment]
I will not support the Celestron OAG. I added a section to the README that documents OAG compatibility. Thanks!

**Comment by Endymion42** [comment]
Here's a completed design for the Celestron OAG.   If acceptable, would you add it to your project for people who want to print and use it themselves?

Regards,
John

[CelestronOAG.zip](https://github.com/jlecomte/ascom-oag-focuser/files/14412291/CelestronOAG.zip)
![IMG_1597](https://github.com/jlecomte/ascom-oag-focuser/assets/92014533/4c20f201-0701-4444-9301-49a9d48c5a95)
![IMG_1596](https://github.com/jlecomte/ascom-oag-focuser/assets/92014533/b36dcbf8-27f9-42de-9d82-66b821954125)
![IMG_1595](https://github.com/jlecomte/ascom-oag-focuser/assets/92014533/58223d00-6638-4f9b-a7c8-af12af10ee83)
![IMG_1594](https://github.com/jlecomte/ascom-oag-focuser/assets/92014533/7af9ca6a-d145-4ce8-a8ff-ab7a830658c5)
![IMG_1592](https://github.com/jlecomte/ascom-oag-focuser/assets/92014533/46cf4dad-bc14-47bf-ae14-602835a6b2d7)

**Comment by Endymion42** [comment]
https://github.com/jlecomte/ascom-oag-focuser/assets/92014533/0007f066-bc40-46ed-a3a4-cc8e99c39e2c

Video in action.

**Comment by jlecomte** [comment]
This is great! I see you attached an OpenSCAD file. Let me see if I can import it in FreeCAD. Thanks!

**Comment by Endymion42** [comment]
OpenSCAD file is a bit messy - this may help:

BaseA is
rotate([180,0,0])
CelestronBaseA();

BaseB is
rotate([180,0,0])
CelestronBaseB();

Cover Plate is
TopCover();


Gear (60 teeth) is
CelestronGear();

Pinion (16 teeth) is
MotorPinion();

**Comment by jlecomte** [comment]
I added the files to the GitHub repository, and credited you for this contribution. Thank you!

**Comment by Endymion42** [comment]
Notes on printing the Celestron OAG parts.

I used 0.2mm with 15% fill.   No supports used on any parts but I do recommend a brim around BaseB as there is a possibility for the print to mess up at the end of the semicircular clamp if you don't.
