### ISSUE TITLE
ASCOM.DarkSkyGeek.FocuserApp.exe unhandled exception

### ISSUE THREAD

**Issue by dlkeng** [jlecomte/ascom-oag-focuser#17]
The **_ASCOM.DarkSkyGeek.FocuserApp.exe_** application generates the following unhandled exception when attempting to "**Set Zero position!**" when clicking the either of the left-arrow buttons when the Focuser is moving.

![Exception](https://github.com/jlecomte/ascom-oag-focuser/assets/2680128/5901fc67-965f-4bf7-8ea6-c3e974461cc7)

This does not occur when attempting to click the right-arrow buttons when the Focuser is moving because the right-arrow buttons are disabled while the Focuser is moving. To be consistent, the left-arrow buttons should also be disabled when the Focuser is moving.

**Comment by dlkeng** [comment]
Correction, I incorrectly described the operations in the reverse order - in actuality, attempting to "Set Zero position!" when the Focuser is moving generates the unhandled exception. When moving the Focuser with the right-arrow buttons, the "**Set Zero position!**" button is disabled preventing the issue, but when moving the Focuser with the left-arrow buttons, the "**Set Zero position!**" is **NOT** disabled. So, the "**Set Zero position!**" should be disabled when moving with any of the arrow buttons.

**Comment by jlecomte** [comment]
Yes, I was able to reproduce. Fix incoming!

**Comment by jlecomte** [comment]
Fixed in release 1.3.1. Thanks!
