### ISSUE TITLE
Adapter for ZWO OAG-L

### ISSUE THREAD

**Issue by naavis** [jlecomte/ascom-oag-focuser#18]
Hi! I'm sorry if this is a dumb question, but could you clarify what the [adapter piece](https://github.com/jlecomte/ascom-oag-focuser/blob/v2/3D_Files/ZWO-OAG-L/STL/Adapter.stl) is needed for when using the OAG motor focuser with the ZWO OAG-L? I printed the parts and am currently assembling them and putting the electronics together. My OAG is at the local observatory in active remote imaging use, so I don't have it at hand now. Maybe the need for the adapter becomes clear when I actually go install the focuser parts, but it would be nice to understand ahead of time what the adapter is for.

Judging by the shape and threading, does it somehow go between the OAG prism and the 1.25" helical focuser?

**Comment by jlecomte** [comment]
For ZWO OAG-L, you can either make the custom designed version, in which case you won’t need an adapter, or you can make the standard version and use the adapter to fit the ZWO helical focuser (M42 female thread)  to the ZWO OAG-L body (4 tiny screws)

**Comment by naavis** [comment]
I am not sure I entirely follow. The OAG-L comes with a helical focuser attached. Why would I need the printed adapter?

Or is the helical focuser on the OAG-L different, and does not fit the printed parts?

**Comment by jlecomte** [comment]
Exactly! You don’t need the adapter. The reason I created the adapter is for people who might own multiple different OAGs and they want to swap the focuser between those OAGs. During the crowdfunding campaign, I had several such requests.

**Comment by naavis** [comment]
Alright, thanks for the clarification. And great project! Solves exactly the problem I've been having a while with my imaging setup.
