### ISSUE TITLE
Scops OAG: access to COM7 denied

### ISSUE THREAD

**Issue by mrnother** [jlecomte/ascom-oag-focuser#5]
Hello, 
I know from the doc and the video, that the app should work fine with a Pegasus Astro "Scops" motorized OAG, too. 
Unfortunately I have an issue here. Ascom Driver were registered without issues and I know that the OAG works on port COM7. When trying to connect to the device with the DarkSkyGeek app, I receive an error: "An error occured while connecting to the focuser". 
I see the issue in the Ascom log, where it says that "access denied opening COM7" and also the Ascom Diagnostic tool says "accees to port COM7 got denied". Any ideas how I can fix this and find out more about the root cause?
Best,
Chris

**Comment by jlecomte** [comment]
This is a generic problem not related to this driver. Something else must be using that port. Use the netstat command to find out.
