### ISSUE TITLE
unhandled exception in focuser app

### ISSUE THREAD

**Issue by CheekyMonkey** [jlecomte/ascom-oag-focuser#6]
Hi Julien

There is a condition in the focuser app that will give an unhandled exception

The maximum target position of the focuser is 4000
Entering a number for the target position greater than 4000 will give an unhandled exception.

See below:

![image](https://github.com/jlecomte/ascom-oag-focuser/assets/537672/f1e4adc2-50ff-4637-af1f-827ef418d323)

By the way, cool project. I made a focuser, but I made a no-solder version :)

![IMG_7766](https://github.com/jlecomte/ascom-oag-focuser/assets/537672/bede56c7-5384-4450-9771-4bbb3d488b8b)

**Comment by jlecomte** [comment]
This is 100% normal and expected. If you want to go beyond 4000 steps, you have to update the maximum position in the driver settings dialog. 4000 is just the default value... I also recommend setting the zero position first. See https://www.youtube.com/watch?v=zPPIgVuxk4Y for more details.

**Comment by CheekyMonkey** [comment]
> This is 100% normal and expected. If you want to go beyond 4000 steps, you have to update the maximum position in the driver settings dialog. 4000 is just the default value... I also recommend setting the zero position first. See https://www.youtube.com/watch?v=zPPIgVuxk4Y for more details.

Ah, thanks.
I need to read the manual :)
