### ISSUE TITLE
What's the value of the capacitor on the PCB?

### ISSUE THREAD

**Issue by MDSchechtman** [jlecomte/ascom-oag-focuser#7]
I couldn't find the value for the capacitor shown on the PCB schematics and final assembly anywhere. 

The small disk capacitor on one of my ULN2003 driver boards measured at 0.01uf but I see you're using an electrolytic which I can only find starting at 0.1uf.

**Comment by jlecomte** [comment]
It’s a bulk capacitor. 10uF works fine.

**Comment by jlecomte** [comment]
I will add that info to the README, I thought it was already there, somewhere.

**Comment by MDSchechtman** [comment]
Great, thank you!
