### ISSUE TITLE
Confused about hole sizes in base and cover

### ISSUE THREAD

**Issue by Endymion42** [jlecomte/ascom-oag-focuser#9]
I'm confused about the hole sizes in the base and cover.  The base holes are significantly smaller than the 4 mount holes in the cover.  As the bolt/screw needs to go through the base into the cover, how is this supposed to work?  

Thanks for any help.  In the mean time I will use a feature in my slicer to fill in the cover holes and replace with smaller diameter holes.

**Comment by jlecomte** [comment]
That is because the large holes are designed to host brass inserts. Please see the BOM. Thanks!

**Comment by Endymion42** [comment]
Thank you for resolving my confusion.   Apologies, I looked around for a BOM but didn't see one listing the brass inserts.   Is it inside the FreeCad files or KiCad files somewhere?

**Comment by jlecomte** [comment]
OK, I forgot to list that in the BOM. Sorry.

**Comment by jlecomte** [comment]
Fixed in [this commit](https://github.com/jlecomte/ascom-oag-focuser/commit/b9ac257cc9738d94fbbac5315695e74b7e7cab98). Thanks!
